import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import matter from 'gray-matter';

function setupArticleFixture() {
  const tmp = mkdtempSync(path.join(os.tmpdir(), 'transcrab-test-'));
  const contentRoot = path.join(tmp, 'content', 'articles');
  const slug = 't1';
  const dir = path.join(contentRoot, slug);
  fs.mkdirSync(dir, { recursive: true });

  const sourceMd = `---\ntitle: Source Title\ndate: 2026-02-07T00:00:00.000Z\nsourceUrl: https://example.com\nlang: source\n---\n\nBody`;
  writeFileSync(path.join(dir, 'source.md'), sourceMd, 'utf8');

  return { tmp, contentRoot, slug, dir };
}

test('apply-translation.mjs: extracts H1 title and writes frontmatter', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  const translated = `# 译文标题\n\n这是正文第一段。\n\n- 列表项\n`;
  const inFile = path.join(tmp, 'translated.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.ok, true);
  assert.equal(out.stage, 'final');

  const zh = readFileSync(path.join(dir, 'zh.md'), 'utf8');
  const parsed = matter(zh);
  assert.equal(parsed.data.title, '译文标题');
  assert.equal(parsed.data.sourceUrl, 'https://example.com');
  assert.equal(parsed.data.lang, 'zh');
  assert.ok(!/^#\s+/m.test(parsed.content.trim()));
  assert.match(parsed.content, /这是正文第一段/);
});

test('apply-translation.mjs: draft stage writes draft+critique for refined flow', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  // mimic refined profile generated by add-url
  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );

  const translated = `# Draft 标题\n\n这是 draft 内容。\n\n\`\`\`js\nconsole.log(1)\n\`\`\``;
  const inFile = path.join(tmp, 'draft.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'draft'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.stage, 'draft');

  const draftPath = path.join(dir, '03-draft.md');
  const critiquePath = path.join(dir, '04-critique.md');
  assert.ok(fs.existsSync(draftPath));
  assert.ok(fs.existsSync(critiquePath));
  assert.ok(!fs.existsSync(path.join(dir, 'zh.md')));

  const critique = readFileSync(critiquePath, 'utf8');
  assert.match(critique, /code-fence-balanced/);
});

test('apply-translation.mjs: draft stage in normal flow does not create critique file', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'normal' }, null, 2),
    'utf8'
  );

  const translated = `# 普通模式标题\n\n普通模式 draft 内容。`;
  const inFile = path.join(tmp, 'normal-draft.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'draft'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  assert.ok(fs.existsSync(path.join(dir, '03-draft.md')));
  assert.ok(!fs.existsSync(path.join(dir, '04-critique.md')));
});

test('apply-translation.mjs: rejects invalid stage', () => {
  const { tmp, contentRoot, slug } = setupArticleFixture();

  const translated = `# T\n\nBody`;
  const inFile = path.join(tmp, 'invalid-stage.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'oops'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /Invalid --stage/);
});

test('apply-translation.mjs: final stage applies punctuation auto-fix and writes lint report', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(path.join(dir, '03-draft.md'), '# Draft\n\nold', 'utf8');

  const translated = `# 最终标题\n\n问题是? 这段中文?`;
  const inFile = path.join(tmp, 'final-lint.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.autoFixed, true);
  assert.ok(fs.existsSync(path.join(dir, 'lint.report.json')));

  const zh = readFileSync(path.join(dir, 'zh.md'), 'utf8');
  assert.match(zh, /问题在于：/);
  assert.match(zh, /中文？/);
});

test('apply-translation.mjs: final stage writes revision notes for refined flow', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(path.join(dir, '03-draft.md'), '# Draft\n\nold', 'utf8');

  const translated = `# 最终标题\n\n最终正文。`;
  const inFile = path.join(tmp, 'final.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  assert.ok(fs.existsSync(path.join(dir, 'zh.md')));
  assert.ok(fs.existsSync(path.join(dir, '05-revision.md')));
});
